services:
  - type: web
    name: cardozo-digital-studio
    env: static
    rootDir: febrosPage/cardozo_landing
    buildCommand: npm install && npm run build
    staticPublishPath: febrosPage/cardozo_landing/dist
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
